/*
 * stellar_lf.h - GENERATED by tools/derive_lf.py. Do not edit.
 *
 * The shipped catalog's own luminosity function and detection
 * limit, measured from assets/catalogs/gaia_stars.bin. The
 * procedural population samples this so generated stars and
 * catalog stars come from one population by construction.
 */
#pragma once

/* Apparent magnitude beyond which the catalog stops seeing things. */
#define CATALOG_MAG_LIMIT   9.49f

/* Outermost catalog row (ly). NOT a completeness radius:
 * this catalog is nowhere volume-complete. */
#define CATALOG_MAX_LY      98937.6f

#define STELLAR_LF_M_MIN    -10
#define STELLAR_LF_M_MAX    13
#define STELLAR_LF_BINS     24

/* stars per ly^3 in each 1-mag bin, starting at STELLAR_LF_M_MIN */
static const float STELLAR_LF[STELLAR_LF_BINS] = {
    7.395173e-16f,   /* M = -10 */
    2.958069e-15f,   /* M = -9 */
    1.151005e-14f,   /* M = -8 */
    2.160236e-13f,   /* M = -7 */
    3.175417e-12f,   /* M = -6 */
    3.254399e-11f,   /* M = -5 */
    4.311426e-10f,   /* M = -4 */
    8.330367e-09f,   /* M = -3 */
    7.505010e-08f,   /* M = -2 */
    3.503075e-07f,   /* M = -1 */
    2.328128e-06f,   /* M = +0 */
    4.409312e-06f,   /* M = +1 */
    1.614089e-05f,   /* M = +2 */
    4.405410e-05f,   /* M = +3 */
    6.820699e-05f,   /* M = +4 */
    8.859706e-05f,   /* M = +5 */
    9.790523e-05f,   /* M = +6 */
    1.089215e-04f,   /* M = +7 */
    1.756831e-04f,   /* M = +8 */
    2.580491e-04f,   /* M = +9 */
    3.166454e-04f,   /* M = +10 */
    4.411524e-04f,   /* M = +11 */
    0.000000e+00f,   /* M = +12 */
    1.551658e-03f,   /* M = +13 */
};

/* Summed LF: implied total stellar density, stars per ly^3.
 * Used to set each procedural cascade's magnitude cut so a
 * coarse cell emits its brightest few members at the correct
 * space density instead of a luminosity-boosted fake. */
#define STELLAR_DENSITY_LY3 3.174186e-03f
